# Generated by Django 3.0.8 on 2020-07-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'CRITICAL'), ('2', 'DEBUG'), ('3', 'ERROR'), ('4', 'WARNING'), ('5', 'INFO')], max_length=20, verbose_name='Level')),
                ('data', models.TextField(verbose_name='Informações')),
                ('shelved', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.Agent')),
            ],
        ),
    ]
